### PR TITLE
Add tests for calling JNI code and improve the JNI call functionality 

### PR DESCRIPTION
**Pull request by zjpetersen**
This PR allows for the native C library to be called in SLIMCurve.java using [NarSystem](https://github.com/maven-nar/nar-maven-plugin) instead of calling NativeLibraryUtil.  Some error checking has also been added for the JNI call.  Unit tests have also been implemented.

### CODE REVIEW

**Comment by ctrueden** [comment]
Thanks Zach. I commented in a couple of places. Once you fix things up, I will review in more detail and then merge it.

**Comment by zjpetersen** [comment]
Thanks for the comments!  I made the suggested changes, let me know what else you see that could be improved.

**Comment by ctrueden** [comment]
Thanks Zach! I reviewed it again. I pinged @paulbarber to take a look at the memory-related changes you propose to `EcfWrapper.c`. The main things left to fix are:

* Conflated changes in a couple of commits, as noted. In particular, 874caf65c5f8b2bee4317ab0a50c90edb986c9b8 reverts a large chunk of changes made in the prior commit, and is unrelated to that commit's stated intent.
* More description of your changes regarding noise models and the new struct there. Those changes are significant enough to warrant an explanation in the commit message. There is also some back-and-forth tugging between commits relating to those changes, which needs to be cleaned up.

Thanks again for your efforts—we are getting close!

**Comment by zjpetersen** [comment]
I did some rebasing and think it looks a lot better now.  Please take a look when you have a chance. Thanks for your help!

**Comment by ctrueden** [comment]
Very sorry for the long delay. It looks nice. Merging before this gets any staler!

**Pull request merged**
